version: '3.8'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb
    ports:
      - "3307:3306"
    volumes:
      - spring-mysql:/var/lib/mysql
    networks:
      - smn-network
 
  mybackend:
    depends_on:
      - mysqldb
    restart: always
    image: hollowmask18/mybackend:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/bootdb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    build:
      context: "./"
      dockerfile: "dockerfile"
    ports:
      - "8080:8080"
    networks:
      - smn-network

networks:
  smn-network:

volumes:
  spring-mysql: